services:
  db:
    container_name: example_postgres
    image: postgres
    environment:
      POSTGRES_USER: springcase
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5431:5432"
    networks:
      - example_network
    restart: unless-stopped

networks:
  example_network:
    driver: bridge

volumes:
  db:
    driver: local